[2025-02-16 16:02:48,102:INFO:main:Welcome to our custom logging data science]
[2025-02-16 16:03:30,464:INFO:main:Welcome to our custom logging data science]
[2025-02-16 16:03:30,465:INFO:main:>>>>>stageData Ingestion Stage started <<<<<]
[2025-02-16 16:03:30,466:INFO:common:yaml file: config/config.yaml loaded successfully]
[2025-02-16 16:03:30,466:INFO:common:yaml file: params.yaml loaded successfully]
[2025-02-16 16:03:30,466:INFO:common:yaml file: schema.yaml loaded successfully]
[2025-02-16 16:03:30,467:INFO:common:created directory at: artifacts]
[2025-02-16 16:03:30,467:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-16 16:03:30,995:INFO:data_ingestion:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 195D:1EB9D8:1157B33:137BE50:67B24C58
Accept-Ranges: bytes
Date: Sun, 16 Feb 2025 21:03:30 GMT
Via: 1.1 varnish
X-Served-By: cache-chi-kigq8000108-CHI
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1739739811.923288,VS0,VE67
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 6faf95bfde7c8ff3033b61b6381a87806b202988
Expires: Sun, 16 Feb 2025 21:08:30 GMT
Source-Age: 0

]
[2025-02-16 16:03:30,997:INFO:main:>>>>>stageData Ingestion Stage completed <<<<<]
[2025-02-19 21:03:55,701:INFO:common:yaml file: config/config.yaml loaded successfully]
[2025-02-19 21:03:55,707:INFO:common:yaml file: params.yaml loaded successfully]
[2025-02-19 21:03:55,710:INFO:common:yaml file: schema.yaml loaded successfully]
[2025-02-19 21:03:55,714:INFO:common:created directory at: artifacts]
[2025-02-23 15:00:23,014:INFO:common:yaml file: config/config.yaml loaded successfully]
[2025-02-23 15:00:23,048:INFO:common:yaml file: params.yaml loaded successfully]
[2025-02-23 15:00:23,055:INFO:common:yaml file: schema.yaml loaded successfully]
[2025-02-23 15:00:23,059:INFO:common:created directory at: artifacts]
[2025-02-23 15:00:23,059:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-23 15:00:23,060:INFO:2639782589:File already exists]
[2025-02-23 15:07:50,667:INFO:common:yaml file: config/config.yaml loaded successfully]
[2025-02-23 15:07:50,669:INFO:common:yaml file: params.yaml loaded successfully]
[2025-02-23 15:07:50,671:INFO:common:yaml file: schema.yaml loaded successfully]
[2025-02-23 15:07:50,673:INFO:common:created directory at: artifacts]
[2025-02-23 15:10:37,924:INFO:common:yaml file: config/config.yaml loaded successfully]
[2025-02-23 15:10:37,926:INFO:common:yaml file: params.yaml loaded successfully]
[2025-02-23 15:10:37,929:INFO:common:yaml file: schema.yaml loaded successfully]
[2025-02-23 15:10:37,930:INFO:common:created directory at: artifacts]
[2025-02-23 15:14:14,175:INFO:common:yaml file: config/config.yaml loaded successfully]
[2025-02-23 15:14:14,177:INFO:common:yaml file: params.yaml loaded successfully]
[2025-02-23 15:14:14,181:INFO:common:yaml file: schema.yaml loaded successfully]
[2025-02-23 15:14:14,182:INFO:common:created directory at: artifacts]
[2025-02-23 15:14:14,183:INFO:common:created directory at: artifacts/data_validation]
[2025-02-23 15:14:24,704:INFO:common:yaml file: config/config.yaml loaded successfully]
[2025-02-23 15:14:24,706:INFO:common:yaml file: params.yaml loaded successfully]
[2025-02-23 15:14:24,709:INFO:common:yaml file: schema.yaml loaded successfully]
[2025-02-23 15:14:24,710:INFO:common:created directory at: artifacts]
[2025-02-23 15:14:24,711:INFO:common:created directory at: artifacts/data_validation]
[2025-02-23 15:15:41,510:INFO:common:yaml file: config/config.yaml loaded successfully]
[2025-02-23 15:15:41,512:INFO:common:yaml file: params.yaml loaded successfully]
[2025-02-23 15:15:41,515:INFO:common:yaml file: schema.yaml loaded successfully]
[2025-02-23 15:15:41,516:INFO:common:created directory at: artifacts]
[2025-02-23 15:15:41,517:INFO:common:created directory at: artifacts/data_validation]
[2025-02-23 15:30:23,872:INFO:main:Welcome to our custom logging data science]
[2025-02-23 15:30:23,872:INFO:main:>>>>>stageData Ingestion Stage started <<<<<]
[2025-02-23 15:30:23,873:INFO:common:yaml file: config/config.yaml loaded successfully]
[2025-02-23 15:30:23,874:INFO:common:yaml file: params.yaml loaded successfully]
[2025-02-23 15:30:23,875:INFO:common:yaml file: schema.yaml loaded successfully]
[2025-02-23 15:30:23,876:INFO:common:created directory at: artifacts]
[2025-02-23 15:30:23,876:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-23 15:30:23,876:INFO:data_ingestion:File already exists]
[2025-02-23 15:30:23,878:INFO:main:>>>>>stageData Ingestion Stage completed <<<<<]
[2025-02-23 15:30:23,878:INFO:main:>>>>>> stage Data Validation stage started <<<<<<]
[2025-02-23 15:30:23,878:ERROR:main:name 'DataValidationTrainingPipeline' is not defined]
Traceback (most recent call last):
  File "/Users/ruilu/datascienceproject/main.py", line 21, in <module>
    data_ingestion = DataValidationTrainingPipeline()
NameError: name 'DataValidationTrainingPipeline' is not defined
[2025-02-23 15:31:05,883:INFO:main:Welcome to our custom logging data science]
[2025-02-23 15:31:05,883:INFO:main:>>>>>stageData Ingestion Stage started <<<<<]
[2025-02-23 15:31:05,884:INFO:common:yaml file: config/config.yaml loaded successfully]
[2025-02-23 15:31:05,884:INFO:common:yaml file: params.yaml loaded successfully]
[2025-02-23 15:31:05,886:INFO:common:yaml file: schema.yaml loaded successfully]
[2025-02-23 15:31:05,886:INFO:common:created directory at: artifacts]
[2025-02-23 15:31:05,886:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-23 15:31:05,886:INFO:data_ingestion:File already exists]
[2025-02-23 15:31:05,888:INFO:main:>>>>>stageData Ingestion Stage completed <<<<<]
[2025-02-23 15:31:05,888:INFO:main:>>>>>> stage Data Validation stage started <<<<<<]
[2025-02-23 15:31:05,888:ERROR:main:name 'DataValidationTrainingPipeline' is not defined]
Traceback (most recent call last):
  File "/Users/ruilu/datascienceproject/main.py", line 21, in <module>
    data_ingestion = DataValidationTrainingPipeline()
NameError: name 'DataValidationTrainingPipeline' is not defined
[2025-02-23 15:31:40,444:INFO:main:Welcome to our custom logging data science]
[2025-02-23 15:31:40,444:INFO:main:>>>>>stageData Ingestion Stage started <<<<<]
[2025-02-23 15:31:40,446:INFO:common:yaml file: config/config.yaml loaded successfully]
[2025-02-23 15:31:40,446:INFO:common:yaml file: params.yaml loaded successfully]
[2025-02-23 15:31:40,447:INFO:common:yaml file: schema.yaml loaded successfully]
[2025-02-23 15:31:40,448:INFO:common:created directory at: artifacts]
[2025-02-23 15:31:40,448:INFO:common:created directory at: artifacts/data_ingestion]
[2025-02-23 15:31:40,448:INFO:data_ingestion:File already exists]
[2025-02-23 15:31:40,449:INFO:main:>>>>>stageData Ingestion Stage completed <<<<<]
[2025-02-23 15:31:40,449:INFO:main:>>>>>> stage Data Validation stage started <<<<<<]
[2025-02-23 15:31:40,451:INFO:common:yaml file: config/config.yaml loaded successfully]
[2025-02-23 15:31:40,451:INFO:common:yaml file: params.yaml loaded successfully]
[2025-02-23 15:31:40,453:INFO:common:yaml file: schema.yaml loaded successfully]
[2025-02-23 15:31:40,453:INFO:common:created directory at: artifacts]
[2025-02-23 15:31:40,453:INFO:common:created directory at: artifacts/data_validation]
[2025-02-23 15:31:40,458:INFO:main:>>>>>> stage Data Validation stage completed <<<<<<

x==========x]
